/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-03-26 04:08:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ajax_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/workspaceSpring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sp_14_ajax/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1552881426430L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script\r\n");
      out.write("  src=\"http://code.jquery.com/jquery-3.3.1.js\"  integrity=\"sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=\"  crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<input type=\"button\" value=\"ajax 문자역\" id=\"ajaxString\"/>\r\n");
      out.write("<input type=\"button\" value=\"ajax Object\" id=\"ajaxObject\"/>\r\n");
      out.write("<input type=\"button\" value=\"ajax List\" id=\"ajaxList\"/>\r\n");
      out.write("<input type=\"button\" value=\"ajax map\" id=\"ajaxMap\"/>\r\n");
      out.write("\t<div id=\"str\"></div>\r\n");
      out.write("\t<div id=\"obj\"></div>\r\n");
      out.write("\t<div id=\"list\"></div>\r\n");
      out.write("\t<div id=\"map\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<form method=\"post\" id=\"frm\">\r\n");
      out.write("\t\t\t번호: <input type=\"text\" name=\"no\"/><br/>\r\n");
      out.write("\t\t\t이름: <input type=\"text\" name=\"name\"/><br/>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"submit\" id=\"btn\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div id=\"result2\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("const ajaxString = document.querySelector(\"#ajaxString\");\r\n");
      out.write("const ajaxObject = document.querySelector(\"#ajaxObject\");\r\n");
      out.write("const ajaxList = document.querySelector(\"#ajaxList\");\r\n");
      out.write("const ajaxMap = document.querySelector(\"#ajaxMap\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("const frm = document.querySelector(\"#frm\");\r\n");
      out.write("\r\n");
      out.write("const btn = document.querySelector(\"#btn\");\r\n");
      out.write("\r\n");
      out.write("const result2 = document.querySelector(\"#result2\");\r\n");
      out.write("const str = document.querySelector(\"#str\");\r\n");
      out.write("const obj = document.querySelector(\"#obj\");\r\n");
      out.write("const list = document.querySelector(\"#list\");\r\n");
      out.write("const map = document.querySelector(\"#map\");\r\n");
      out.write("\r\n");
      out.write("//const ajaxString = document.querySelector(\"#ajaxString\");\r\n");
      out.write("\r\n");
      out.write("\tfunction event(){\r\n");
      out.write("\t\tajaxString.addEventListener(\"click\",function(){\r\n");
      out.write("\t\t\tlet uri =\"/webAjax/ajaxString\";\r\n");
      out.write("\t\t\tlet param = \"no=123&name=이순신\";\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\t\turl : uri,\r\n");
      out.write("\t\t\t\tdata : param,\r\n");
      out.write("\t\t\t\tcontentType : 'application/json;charset=UTF-8',\r\n");
      out.write("\t\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\t\tstr.innerHTML=result;\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(error){\r\n");
      out.write("\t\t\t\t\tstr.innerHTML=error.responseText;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tajaxObject.addEventListener(\"click\",function(){\r\n");
      out.write("\t\t\tlet uri =\"/webAjax/ajaxObject\";\r\n");
      out.write("\t\t\tlet param = \"no=1111&name=홍길동\";\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\turl : uri,\r\n");
      out.write("\t\t\t\tdata : param,\r\n");
      out.write("\t\t\t\tcontentType : 'application/json;charset=UTF-8',\r\n");
      out.write("\t\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\t\tconst str = \"no=\" + result.no +\", name=\"+result.name;\r\n");
      out.write("\t\t\t\t\tobj.innerHTML= str;\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(error){\r\n");
      out.write("\t\t\t\t\tobj.innerHTML=error.responseText;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tajaxList.addEventListener(\"click\",function(){\r\n");
      out.write("\t\t\tlet uri =\"/webAjax/ajaxList\";\r\n");
      out.write("\t\t\tlet param = \"no=2222&name=경복궁\";\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\turl : uri,\r\n");
      out.write("\t\t\t\tdata : param,\r\n");
      out.write("\t\t\t\tcontentType : 'application/json;charset=UTF-8',\r\n");
      out.write("\t\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\t\t//foreach\r\n");
      out.write("\t\t\t\t\tlet result3 = $(result);\r\n");
      out.write("\t\t\t\t\tlist.innerHTML = result3;\r\n");
      out.write("\t\t\t\t\tlet txt =\"<ul>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tresult3.each(function(idx,data){\r\n");
      out.write("\t\t\t\t\t\ttxt += \"<li>no :\"+data.no+\" name : \"+data.name+\"</li>\"\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\ttxt+= \"</ul>\"\r\n");
      out.write("\t\t\t\t\tlist.innerHTML = txt;\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(error){\r\n");
      out.write("\t\t\t\t\tlist.innerHTML=error.responseText;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//map\r\n");
      out.write("\t\tajaxMap.addEventListener(\"click\",function(){\r\n");
      out.write("\t\t\tlet uri =\"/webAjax/ajaxMap\";\r\n");
      out.write("\t\t\tlet param = \"no=3333&name=창덕궁\";\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\turl : uri,\r\n");
      out.write("\t\t\t\tdata : param,\r\n");
      out.write("\t\t\t\tcontentType : 'application/json;charset=UTF-8',\r\n");
      out.write("\t\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\t\tlet txt = \"<ul>\";\r\n");
      out.write("\t\t\t\t\ttxt += \"<li>\"+result.A.no +\",\"+ result.A.name+ \"</li>\"\r\n");
      out.write("\t\t\t\t\ttxt += \"<li>\"+result.B.no +\",\"+ result.B.name+ \"</li>\"\r\n");
      out.write("\t\t\t\t\ttxt += \"<li>\"+result.C.no +\",\"+ result.C.name+ \"</li>\"\r\n");
      out.write("\t\t\t\t\ttxt += \"<li>\"+result.D.no +\",\"+ result.D.name+ \"</li></ul>\"\r\n");
      out.write("\t\t\t\t\tmap.innerHTML = txt;\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(error){\r\n");
      out.write("\t\t\t\t\tmap.innerHTML=error.responseText;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tbtn.addEventListener(\"click\",function(){\r\n");
      out.write("\t\t\t//event.preventDefault();\r\n");
      out.write("\t\t\tlet uri =\"/webAjax/ajaxForm\";\r\n");
      out.write("\t\t\tlet param = $(\"#frm\").serialize();\r\n");
      out.write("\t\t\tconsole.log(param);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\turl : uri,\r\n");
      out.write("\t\t\t\tdata : param,\r\n");
      out.write("\t\t\t\tcontentType : 'application/json;charset=UTF-8',\r\n");
      out.write("\t\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\t\tresult2.innerHTML = result\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(error){\r\n");
      out.write("\t\t\t\t\tresult2.innerHTML = error.responseText;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tevent();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
